### ISSUE TITLE
Unable to create multiple Metric prefix

### ISSUE THREAD

**Issue by ergauravagg** [Appdynamics/url-monitoring-extension#8]
Hi Team,

I am getting error "Error Creating Environment Task while parsing a block collection "when i am trying to create multiple Metric prefix based on different URLs to monitor.

We have multiple applications and hence multiple URL's we are trying to ping all the URL's from single machine and hence we are trying to create multiple modes (Custom Metrics | URL Monitor|mode1 , Custom Metrics | URL Monitor|mode 2) after few set of url's to segregate same in Metric browser.

However on running same it is throwing error, but when i run same for single MetrixPrefix it works fine.

My Config.yml is something as below.

clientConfig:
    maxConnTotal:    1000
    maxConnPerRoute: 1000
    ignoreSslErrors: true
    userAgent:       Mozilla/5.0 (compatible; AppDynamics UrlMonitor; http://www.appdynamics.com/)

defaultParams:
    method:          GET
    socketTimeout:   30000
    connectTimeout:  30000
    numAttempts:     1

#Sites that need to be monitored

sites:

  - name:     ING_Webservice_35
    url:      http://172.23.103.35:9086/PFTXLifeWebservices/services/TXLifeService

metricPrefix: Custom Metrics|URLMonitor|ING

  - name:     ING_AppServer_36
    url:      http://172.23.103.36:9081/ingenium/SsoIndex.jsp

#prefix used to show up metrics in AppDynamics
#This will create it in specific Tier. Replace
#metricPrefix: Server|Component:<TierID>|Custom Metrics|URLMonitor|
#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|URLMonitor|ING_1

Regards
Gaurav Aggarwal

**Comment by BalakrishnaV** [comment]
Hi Gaurav,

You shouldn't do that. metricPrefix is common for all the urls and is the root metric path. The field "name" available for every site (url) takes care of your requirement.
Ex: 

```
sites:
  - name:  ING_Webservice_35
     url:      ttp://172.23.103.35:9086/PFTXLifeWebservices/services/TXLifeService


metricPrefix: Custom Metrics|URLMonitor|
```

Now the metrics are reported at "Custom Metrics |URLMonitor | ING_Webservice_35"

In case of further issues, please raise a help ticket at AppDynamics Support.

Thanks

**Comment by ergauravagg** [comment]
Hi Bala,

My main aim here is to use single machine agent for URL monitoing of my 10 applications and i wanted to segregrate all applications inside URL Monitor so naming will only make url under Unique name in URL monitoring but if i wanted to group the Names then is there a way.



Regards
GAurav

**Comment by BalakrishnaV** [comment]
Hi Gaurav,

URL grouping is not supported as of now. You could always fork the code from here and make changes to suit your use case.

Thanks
